### ISSUE TITLE
Allow for terrain to generate out past 2^31 blocks

### ISSUE THREAD

**Issue by muzikbike** [ThisTestUser/FarLandsMod#5]
This is a pretty ridiculous idea, and would itself take a comparably ridiculous amount of work and code to get it to actually function (some minor success has been had before, see the link below). But were the 32-bit block and chunk limits removed and the limits instead moved to 64 bits, we could encounter the Fartherer and Farthest Lands in their usual positions, as well as the Java Stripe Lands at 2^53 blocks.

https://github.com/geniiii/FarLands/issues/13

**Comment by ThisTestUser** [comment]
Since there are lots of instances that depend on the XYZ coords being less than 2^31, pushing beyond the limit via mixins or Forge transformers will probably be close to impossible. What would be easier to do is to just "offset" the terrain like this: https://github.com/ThisTestUser/FarLandsChronicles/blob/master/Chapter%202%20-%20The%20Far%20Lands%20in%201.12.2/Part%202.5%20-%20Shifting%20the%20Far%20Lands.md

**Comment by ThisTestUser** [comment]
I tried the "offsetting" method in MCP 1.12 and managed to get the fartherer/farthest lands to generate at spawn, and there wasn't anything special about the terrain. The only feature I saw was that the farthest lands only reaches up to ~225 blocks, but otherwise not much difference from the farther lands.

**Comment by muzikbike** [comment]
Closing for now as this is an infeasible target especially for such a lightweight mod.
